# PostgreSQL database configuration

connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *connection
  database: naf_development

test:
  <<: *connection
  database: naf_test

production:
  <<: *connection
  database: naf_production
  username: naf_admin
  password: <%= ENV['NAF_DATABASE_PASSWORD'] %>