// Accounts
export const ACCOUNT_LIST_REQUEST = "ACCOUNT_LIST_REQUEST";
export const ACCOUNT_LIST_SUCCESS = "ACCOUNT_LIST_SUCCESS";
export const ACCOUNT_LIST_FAIL = "ACCOUNT_LIST_FAIL";
export const ACCOUNT_LIST_RESET = "ACCOUNT_LIST_RESET";
export const ACCOUNT_LIST_UPDATE_FAVORITE = "ACCOUNT_LIST_UPDATE_FAVORITE";
export const ACCOUNT_LIST_UPDATE_UNFAVORITE = "ACCOUNT_LIST_UPDATE_UNFAVORITE";
export const ACCOUNT_FAVORITE_REQUEST = "ACCOUNT_FAVORITE_REQUEST";
export const ACCOUNT_FAVORITE_SUCCESS = "ACCOUNT_FAVORITE_SUCCESS";
export const ACCOUNT_FAVORITE_FAIL = "ACCOUNT_FAVORITE_FAIL";
export const ACCOUNT_FAVORITE_RESET = "ACCOUNT_FAVORITE_RESET";
export const ACCOUNT_UNFAVORITE_REQUEST = "ACCOUNT_UNFAVORITE_REQUEST";
export const ACCOUNT_UNFAVORITE_SUCCESS = "ACCOUNT_UNFAVORITE_SUCCESS";
export const ACCOUNT_UNFAVORITE_FAIL = "ACCOUNT_UNFAVORITE_FAIL";
export const ACCOUNT_UNFAVORITE_RESET = "ACCOUNT_UNFAVORITE_RESET";